name: ci

on: [push]

jobs:
  ci:
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache ~/.npm directory
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run lint
